stages:
  - build
  - deploy


# fdm283_build:
#     stage: build
#     tags:
#       - 283-cicd
#     script: 
#         - echo "Fetching devops scripts..."
#         - git clone http://Adarsha:adak6128@172.30.58.37/marketplace/devops.git
#         - cd devops
#         - ansible-playbook -i inventory create_build.yml

fdm283_deploy:
    stage: deploy
    tags:
      - 283-cicd
    script:
        - git clone http://Adarsha:adak6128@172.30.58.37/marketplace/devops.git
        - cd devops
        - git checkout fdm283
        - cd Dev-Upgrades
        - mkdir -p ~/.ssh
        - echo "$PEM_KEY_PATH" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo "PEM file written to ~/.ssh/id_rsa"
        - echo -e "[servers]\n$IP_283server ansible_user=rocky ansible_ssh_private_key_file=~/.ssh/id_rsa" > inventory.ini
        - ansible-playbook -i inventory AP/upgradeap.yml
        # - chmod 600 *.pem
        # - ansible-playbook replaceip.yml 
        # - ansible-playbook -i devhosts1 --extra-vars "@portals.yml" AP/upgradeap.yml