stages:
  - verify
  - build
  - deploy

fdm283_build:
    stage: build
    tags:
      - 283-cicd
    script: 
        - echo "Running Ansible playbook with branch name: $CI_COMMIT_BRANCH"
        - echo "Fetching devops scripts..."
        - git clone http://$username:$password@172.30.58.37/marketplace/devops.git
        - cd devops
        - ansible-playbook -i inventory portals/AP/create_build.yml --extra-vars "branchname=$CI_COMMIT_BRANCH"
    only:
        - fdm283
fdm283_deploy:
    stage: deploy
    tags:
      - 283-cicd
    script:
        - git clone http://$username:$password@172.30.58.37/marketplace/devops.git
        - cd devops
        - git checkout fdm283
        - cd Dev-Upgrades
        - chmod 600 $SSH_PRIVATE_KEY
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
        - eval `ssh-agent -s`
        - ssh-add $SSH_PRIVATE_KEY
        - echo -e "[ap]\n$IP_283 ansible_user=rocky ansible_ssh_private_key_file=$SSH_PRIVATE_KEY" > inventory
        - ansible-playbook -i inventory --extra-vars "@portals.yml" AP/upgradeap.yml
    only:
        - fdm283