stages:
  - build
  - deploy


fdm283:
    stage: build
    tags:
      - ams-cicd 
    script: 
        - echo "Fetching devops scripts..."
        - git clone http://Adarsha:adak6128@172.30.58.37/marketplace/devops.git
        - cd devops
        - ansible-playbook -i inventory create_build.yml