stages:
  - build
  - deploy


fdm283:
    stage: build
    tags:
      - ams-cicd 
    script: 
        - echo "Fetching devops scripts..."
        - git clone http://$GIT_USERNAME:$GIT_PASSWORD@172.30.58.37/marketplace/devops.git